# Generated by Django 5.0.2 on 2024-02-20 15:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MV4',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Id')),
                ('filename', models.CharField(max_length=50, verbose_name='Filename')),
                ('processing', models.BooleanField(verbose_name='Processing')),
                ('processing_success', models.BooleanField(blank=True, default=None, null=True, verbose_name='Processing success')),
                ('file', models.FileField(upload_to='mv4/', verbose_name='File')),
            ],
        ),
    ]
