
services:

  wsgiapplication:
    build:
      context: ./../../../src
      dockerfile: Dockerfile
    restart: always
    command: ./.entrypoints/wsgi.sh
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    env_file:
      - ./.docker.dev-server.env
    depends_on:
      - db

  db:
    image: postgres:14
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.docker.dev-server.env
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    env_file:
      - ./.docker.dev-server.env
    ports:
      - "5050:80"
    depends_on:
      - db
    volumes:
      - pgadmin_data:/var/lib/pgadmin
  
  nginx:
    build:
      context: ./../nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    volumes:
      - static:/var/www/html/static
      - media:/var/www/html/media
    depends_on:
      - wsgiapplication
  
  redis:
    image: redis:7-alpine

  celery_worker:
    build:
      context: ./../../../src
      dockerfile: Dockerfile
    command: ./.entrypoints/celery_worker.sh
    env_file:
      - ./.docker.dev-server.env
    depends_on:
      - redis
      - db
    
  celery_flower:
    build:
      context: ./../../../src
      dockerfile: Dockerfile
    command: ./.entrypoints/celery_flower.sh
    ports:
      - 5557:5555
    env_file:
      - ./.docker.dev-server.env
    depends_on:
      - redis
      - db


volumes:
  postgres_data:
  pgadmin_data:
  static:
  media: